import {
  doc,
  getDoc,
  deleteDoc,
  collection,
  getDocs,
} from "firebase/firestore";

import { firestore, FireModel } from "../src/client.js";
import { terminateFirebase } from "../src/firebase/client.js";

class Animal extends FireModel {
  static collectionPath = "Animals";
  static useAutonumber = false;
  static classProps = {
    code: { type: String, default: "", required: false },
    name: { type: String, default: "", required: true },
    type: {
      type: String,
      default: "",
      required: true,
      validator: (v) => ["dog", "cat"].includes(v),
    },
  };
  static tokenFields = ["name"];

  beforeCreate() {
    return new Promise((resolve, reject) => {
      if (!this.name) {
        reject(new Error(`name is required to input.`));
      }
      resolve();
    });
  }

  beforeUpdate() {
    return new Promise((resolve, reject) => {
      if (!this.name) {
        reject(new Error(`name is required to input.`));
      }
      resolve();
    });
  }
}

class AnimalAutonumber extends Animal {
  static collectionPath = "AnimalsAutonumber";
  static useAutonumber = true;
  static classProps = {
    code: { type: String, default: "", required: false },
    name: { type: String, default: "", required: true },
    type: {
      type: String,
      default: "",
      required: true,
      validator: (v) => ["dog", "cat"].includes(v),
    },
  };
}

class Autonumber extends FireModel {
  static collectionPath = "Autonumbers";
  static useAutonumber = false;
  static classProps = {
    collection: { type: String, default: "", required: true },
    current: { type: Number, default: 0, required: true },
    length: { type: Number, default: 4, required: true },
    field: { type: String, default: "code", required: true },
    status: { type: Boolean, default: true, required: true },
  };
  async create({ transaction = null, callBack = null } = {}) {
    return await super.create({
      docId: this.collection,
      useAutonumber: false,
      transaction,
      callBack,
    });
  }
}

describe("FireModel クライアントテスト", () => {
  /**
   * create 実行時、beforeCreate が resolve を返すことで処理が中断されることを確認します。
   */
  test("Interrupt create document processing by 'beforeCreate'.", async () => {
    const model = new Animal();
    await expect(model.create()).rejects.toThrow(`name is required to input.`);
  });

  /**
   * create 実行時、validate が resolve を返すことで処理が中断されることを確認します。
   */
  test("Interrupt create document processing by 'validate'.", async () => {
    const model = new Animal({ name: "tama" });

    // create will be rejected because `type` is required.
    await expect(model.create()).rejects.toThrow(`type is required.`);

    model.type = "mouse";

    // create will be rejected because `mouse` is not allowed.
    await expect(model.create()).rejects.toThrow(
      `Invalid value at type. value: mouse`
    );
  });

  /**
   * create 実行時、自動採番ドキュメントが存在しない場合にエラーとなること。
   */
  test("Interrupt create document processing due to 'Autonumber' document is not found.", async () => {
    const model = new AnimalAutonumber({ name: "tama", type: "cat" });
    await expect(model.create()).rejects.toBeDefined();
  });

  /**
   * create 実行時、自動採番が最大値に達している場合にエラーとなること。
   */
  test("Interrupt create document processing due to 'Autonumber' is maximum value.", async () => {
    const model = new AnimalAutonumber({ name: "tama", type: "cat" });
    const autonumber = new Autonumber({
      collection: "AnimalsAutonumber",
      current: 9,
      length: 1,
    });
    const autonumberDocRef = await autonumber.create();
    await expect(model.create()).rejects.toBeDefined();
    await deleteDoc(autonumberDocRef);
  });

  /**
   * create でドキュメントが正常に作成されること。
   */
  test("The document should be created successfully with create.", async () => {
    const model = new Animal({ name: "tama", type: "cat" });
    const docRefs = await Promise.all([
      model.create(),
      model.create({ docId: "FIXED" }),
    ]);
    expect(docRefs[0]).not.toBeFalsy();
    expect(docRefs[1]).not.toBeFalsy();
    expect(docRefs[1].id).toBe("FIXED");
    for (const docRef of docRefs) {
      await deleteDoc(docRef);
    }
  });

  /**
   * 自動採番によるコード生成がされた状態でドキュメントが作成されること
   */
  test("Document should be created with code generated by Autonumber.", async () => {
    // create autonumber document.
    const autonumber = new Autonumber({ collection: "AnimalsAutonumber" });
    const autonumberDocRef = await autonumber.create();

    // create animal document.
    const model = new AnimalAutonumber({ name: "tama", type: "cat" });
    const docRef = await model.create();

    // check the code is set '0001'.
    expect(model.code).toBe("0001");

    await deleteDoc(autonumberDocRef);
    await deleteDoc(docRef);
  });

  /**
   * create 関数で useAutonumber が false であった場合にコードが生成されないこと。
   */
  test("Do not generate code by Autonumber using 'useAutonumber' argument at create.", async () => {
    // create autonumber document.
    const autonumber = new Autonumber({ collection: "AnimalsAutonumber" });
    const autonumberDocRef = await autonumber.create();

    // create animal document.
    const model = new AnimalAutonumber({ name: "tama", type: "cat" });
    const docRef = await model.create({ useAutonumber: false });

    expect(model.code).toBeFalsy();

    await deleteDoc(autonumberDocRef);
    await deleteDoc(docRef);
  });

  /**
   * fetch の動作を確認します。
   */
  test("fetch", async () => {
    const model = new FireModel();
    const docRef = await model.create({
      docId: "FETCH-DOCUMENT",
      useAutonumber: false,
    });
    let fetchResult = await model.fetch("COULD-NOT-FETCH-DOCUMENT");
    expect(fetchResult).toBe(false);
    expect(model.docId).toBeFalsy();
    fetchResult = await model.fetch(docRef.id);
    expect(fetchResult).toBe(true);
    expect(model.docId).toBe("FETCH-DOCUMENT");
    await deleteDoc(docRef);
  });

  /**
   * fetchDoc の動作を確認します。
   */
  test("fetchDoc", async () => {
    const model = new FireModel();
    const docRef = await model.create({
      docId: "FETCH-DOCUMENT",
      useAutonumber: false,
    });
    let fetchResult = await model.fetchDoc("COULD-NOT-FETCH-DOCUMENT");
    expect(fetchResult).toBe(null);
    model.docId = "DUMMY-ID";
    fetchResult = await model.fetchDoc("FETCH-DOCUMENT");
    expect(fetchResult?.docId).toBe("FETCH-DOCUMENT");
    expect(model.docId).toBe("DUMMY-ID");
    await deleteDoc(docRef);
  });

  /**
   * fetchDocs の動作を確認します。
   */
  test("fetchDocs", async () => {
    class Animal extends FireModel {
      static collectionPath = "Animals";
      static useAutonumber = false;
      static classProps = {
        name: { type: String, default: "", required: true },
        type: { type: String, default: "", required: true },
      };
      static tokenFields = ["name"];
    }
    const model = new Animal({ name: "mike", type: "cat" });
    await model.create();
    model.name = "tama";
    model.type = "cat";
    await model.create();
    model.name = "pochi";
    model.type = "dog";
    await model.create();
    model.name = "tamao";
    model.type = "dog";
    await model.create();
    model.name = "tamako";
    model.type = "dog";
    await model.create();
    model.name = "koike";
    model.type = "human";
    await model.create();

    const cats = await model.fetchDocs({
      constraints: [["where", "type", "==", "cat"]],
    });
    expect(cats.length).toBe(2);
    const dogs = await model.fetchDocs({
      constraints: [["where", "type", "==", "dog"]],
    });
    expect(dogs.length).toBe(3);
    const ngram = await model.fetchDocs({ constraints: "tama" });
    expect(ngram.length).toBe(3);
    const colRef = collection(firestore, "Animals");
    const docsSnapshot = await getDocs(colRef);
    for (const docRef of docsSnapshot.docs.map((doc) => doc.ref)) {
      await deleteDoc(docRef);
    }
  });

  /**
   * update の動作を確認します。
   */
  test("update", async () => {
    class Animal extends FireModel {
      static collectionPath = "Animals";
      static useAutonumber = false;
      static classProps = {
        name: { type: String, default: "", required: true },
        type: { type: String, default: "", required: true },
      };
      static tokenFields = ["name"];
    }
    const model = new Animal({ name: "mike", type: "cat" });
    const docRef = await model.create();
    model.name = "tama";
    await model.update();
    model.name = "mike";
    await model.fetch(model.docId);
    expect(model.name).toBe("tama");
    await deleteDoc(docRef);
  });

  /**
   * delete の動作を確認します。
   */
  test("delete document as physical.", async () => {
    const model = new Animal({ name: "mike", type: "cat" });
    const docRef = await model.create();
    await model.delete();
    const isFetched = await model.fetch(docRef.id);
    expect(isFetched).toBe(false);
  });

  /**
   * delete の動作を確認します。
   */
  test("delete document as logical.", async () => {
    class TestModel extends Animal {
      static logicalDelete = true;
    }
    const model = new TestModel({ name: "mike", type: "cat" });
    const docRef = await model.create();
    await model.delete();
    const isFetched = await model.fetch(docRef.id);
    expect(isFetched).toBe(false);
    const archiveDocRef = doc(firestore, "Animals_archive", docRef.id);
    const archiveDocSnap = await getDoc(archiveDocRef);
    expect(archiveDocSnap.exists()).toBe(true);
    await deleteDoc(archiveDocRef);
  });

  /**
   * restore の動作を確認します。
   */
  test("restore document.", async () => {
    class TestModel extends Animal {
      static logicalDelete = true;
    }
    const model = new TestModel({ name: "mike", type: "cat" });
    const docRef = await model.create();
    await model.delete();
    const restoreDocRef = await TestModel.restore(docRef.id);
    await deleteDoc(restoreDocRef);
  });

  /**
   * subscribe の動作を確認します。
   */
  test("subscribe document.", async () => {
    const model = new Animal({ name: "mike", type: "cat" });
    const docRef = await model.create();
    const otherModel = new Animal();
    otherModel.subscribe(docRef.id);
    await new Promise((resolve) => setTimeout(resolve, 1000));
    expect(otherModel.name).toBe("mike");
    otherModel.unsubscribe();
    await deleteDoc(docRef);
  });

  /**
   * subscribeDocs の動作を確認します。
   */
  test("subscribeDocs document.", async () => {
    // 作成するドキュメントのリストを用意
    const animals = [
      { name: "mike", type: "cat" },
      { name: "tama", type: "cat" },
      { name: "pon", type: "cat" },
      { name: "pochi", type: "dog" },
      { name: "miyake", type: "dog" },
      { name: "pokky", type: "dog" },
      { name: "toppo", type: "dog" },
    ];

    const docRefs = [];

    // リスト分のドキュメントを作成
    const model = new Animal();
    for (const animal of animals) {
      model.initialize(animal);
      const docRef = await model.create();
      docRefs.push(docRef);
    }

    // リスナー用のモデルを用意
    const listenerModel = new Animal();

    // type = 'cat' のドキュメントを購読
    const typeDocs = listenerModel.subscribeDocs([
      ["where", "type", "==", "cat"],
    ]);

    // 購読が完了するまで待機
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // 購読したドキュメントをカウント
    const typeLength = typeDocs.length;

    // N-Gram ( name includes 'po' ) のドキュメントを購読
    const nameDocs = listenerModel.subscribeDocs("po");

    // 購読が完了するまで待機
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // 購読したドキュメントをカウント
    const nameLength = nameDocs.length;

    // 複合検索 のドキュメントを購読
    const nameAndTypeDocs = listenerModel.subscribeDocs("po", [
      ["where", "type", "==", "cat"],
    ]);

    // 購読が完了するまで待機
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // 購読したドキュメントをカウント
    const nameTypeLength = nameAndTypeDocs.length;

    // 購読を解除
    listenerModel.unsubscribe();

    // 作成したドキュメントを削除
    for (const docRef of docRefs) {
      await deleteDoc(docRef);
    }

    // 読み込んだドキュメント数の確認
    expect(typeLength).toBe(3);
    expect(nameLength).toBe(4);
    expect(nameTypeLength).toBe(1);
  });

  afterAll(() => {
    terminateFirebase();
  });
});
