/**
 * サーバー側 FireModel 単体テスト
 */
const { firestore, FireModel } = require("air-firebase-v2/server");
const functions = require("firebase-functions-test")({
  projectId: "air-firebase-v2",
});

class Animal extends FireModel {
  static collectionPath = "Animals";
  static useAutonumber = false;
  static classProps = {
    code: { type: String, default: "", required: false },
    name: { type: String, default: "", required: true },
    type: {
      type: String,
      default: "",
      required: true,
      validator: (v) => ["dog", "cat"].includes(v),
    },
  };
  static tokenFields = ["name"];

  beforeCreate() {
    return new Promise((resolve, reject) => {
      if (!this.name) {
        reject(new Error(`name is required to input.`));
      }
      resolve();
    });
  }

  beforeUpdate() {
    return new Promise((resolve, reject) => {
      if (!this.name) {
        reject(new Error(`name is required to input.`));
      }
      resolve();
    });
  }
}

class AnimalAutonumber extends Animal {
  static collectionPath = "AnimalsAutonumber";
  static useAutonumber = true;
  static classProps = {
    code: { type: String, default: "", required: false },
    name: { type: String, default: "", required: true },
    type: {
      type: String,
      default: "",
      required: true,
      validator: (v) => ["dog", "cat"].includes(v),
    },
  };
}

class Autonumber extends FireModel {
  static collectionPath = "Autonumbers";
  static useAutonumber = false;
  static classProps = {
    collection: { type: String, default: "", required: true },
    current: { type: Number, default: 0, required: true },
    length: { type: Number, default: 4, required: true },
    field: { type: String, default: "code", required: true },
    status: { type: Boolean, default: true, required: true },
  };
  async create({ transaction = null, callBack = null } = {}) {
    return await super.create({
      docId: this.collection,
      useAutonumber: false,
      transaction,
      callBack,
    });
  }
}

describe("FireModel クライアントテスト", () => {
  /**
   * create 実行時、beforeCreate が resolve を返すことで処理が中断されることを確認します。
   */
  test("Interrupt create document processing by 'beforeCreate'.", async () => {
    const model = new Animal();
    await expect(model.create()).rejects.toThrow(`name is required to input.`);
  });

  /**
   * create 実行時、validate が resolve を返すことで処理が中断されることを確認します。
   */
  test("Interrupt create document processing by 'validate'.", async () => {
    const model = new Animal({ name: "tama" });

    // create will be rejected because `type` is required.
    await expect(model.create()).rejects.toThrow(`type is required.`);

    model.type = "mouse";

    // create will be rejected because `mouse` is not allowed.
    await expect(model.create()).rejects.toThrow(
      `Invalid value at type. value: mouse`
    );
  });

  /**
   * create 実行時、自動採番ドキュメントが存在しない場合にエラーとなること。
   */
  test("Interrupt create document processing due to 'Autonumber' document is not found.", async () => {
    const model = new AnimalAutonumber({ name: "tama", type: "cat" });
    await expect(model.create()).rejects.toBeDefined();
  });

  /**
   * create 実行時、自動採番が最大値に達している場合にエラーとなること。
   */
  test("Interrupt create document processing due to 'Autonumber' is maximum value.", async () => {
    const model = new AnimalAutonumber({ name: "tama", type: "cat" });
    const autonumber = new Autonumber({
      collection: "AnimalsAutonumber",
      current: 9,
      length: 1,
    });
    const autonumberDocRef = await autonumber.create();
    await expect(model.create()).rejects.toBeDefined();
    await autonumberDocRef.delete();
  });

  /**
   * create でドキュメントが正常に作成されること。
   */
  test("The document should be created successfully with create.", async () => {
    const model = new Animal({ name: "tama", type: "cat" });
    const docRefs = await Promise.all([
      model.create(),
      model.create({ docId: "FIXED" }),
    ]);
    expect(docRefs[0]).not.toBeFalsy();
    expect(docRefs[1]).not.toBeFalsy();
    expect(docRefs[1].id).toBe("FIXED");
    for (const docRef of docRefs) {
      await docRef.delete();
    }
  });

  /**
   * 自動採番によるコード生成がされた状態でドキュメントが作成されること
   */
  test("Document should be created with code generated by Autonumber.", async () => {
    // create autonumber document.
    const autonumber = new Autonumber({ collection: "AnimalsAutonumber" });
    const autonumberDocRef = await autonumber.create();

    // create animal document.
    const model = new AnimalAutonumber({ name: "tama", type: "cat" });
    const docRef = await model.create();

    // check the code is set '0001'.
    expect(model.code).toBe("0001");

    await autonumberDocRef.delete();
    await docRef.delete();
  });

  /**
   * create 関数で useAutonumber が false であった場合にコードが生成されないこと。
   */
  test("Do not generate code by Autonumber using 'useAutonumber' argument at create.", async () => {
    // create autonumber document.
    const autonumber = new Autonumber({ collection: "AnimalsAutonumber" });
    const autonumberDocRef = await autonumber.create();

    // create animal document.
    const model = new AnimalAutonumber({ name: "tama", type: "cat" });
    const docRef = await model.create({ useAutonumber: false });

    expect(model.code).toBeFalsy();

    await autonumberDocRef.delete();
    await docRef.delete();
  });

  /**
   * fetch の動作を確認します。
   */
  test("fetch", async () => {
    const model = new FireModel();
    const docRef = await model.create({
      docId: "FETCH-DOCUMENT",
      useAutonumber: false,
    });
    let fetchResult = await model.fetch("COULD-NOT-FETCH-DOCUMENT");
    expect(fetchResult).toBe(false);
    expect(model.docId).toBeFalsy();
    fetchResult = await model.fetch(docRef.id);
    expect(fetchResult).toBe(true);
    expect(model.docId).toBe("FETCH-DOCUMENT");
    await docRef.delete();
  });

  /**
   * fetchDoc の動作を確認します。
   */
  test("fetchDoc", async () => {
    const model = new FireModel();
    const docRef = await model.create({
      docId: "FETCH-DOCUMENT",
      useAutonumber: false,
    });
    let fetchResult = await model.fetchDoc("COULD-NOT-FETCH-DOCUMENT");
    expect(fetchResult).toBe(null);
    model.docId = "DUMMY-ID";
    fetchResult = await model.fetchDoc("FETCH-DOCUMENT");
    expect(fetchResult?.docId).toBe("FETCH-DOCUMENT");
    expect(model.docId).toBe("DUMMY-ID");
    await docRef.delete();
  });

  /**
   * fetchDocs の動作を確認します。
   */
  test("fetchDocs", async () => {
    class Animal extends FireModel {
      static collectionPath = "Animals";
      static useAutonumber = false;
      static classProps = {
        name: { type: String, default: "", required: true },
        type: { type: String, default: "", required: true },
      };
      static tokenFields = ["name"];
    }
    const model = new Animal({ name: "mike", type: "cat" });
    await model.create();
    model.name = "tama";
    model.type = "cat";
    await model.create();
    model.name = "pochi";
    model.type = "dog";
    await model.create();
    model.name = "tamao";
    model.type = "dog";
    await model.create();
    model.name = "tamako";
    model.type = "dog";
    await model.create();
    model.name = "koike";
    model.type = "human";
    await model.create();

    const cats = await model.fetchDocs({
      constraints: [["where", "type", "==", "cat"]],
    });
    expect(cats.length).toBe(2);
    const dogs = await model.fetchDocs({
      constraints: [["where", "type", "==", "dog"]],
    });
    expect(dogs.length).toBe(3);
    // const ngram = await model.fetchDocs({ constraints: "tama" });
    // expect(ngram.length).toBe(3);
    await expect(model.fetchDocs({ constraints: "tama" })).rejects.toThrow();
    const colRef = firestore.collection("Animals");
    const docsSnapshot = await colRef.get();
    for (const docRef of docsSnapshot.docs.map((doc) => doc.ref)) {
      await docRef.delete();
    }
  });

  /**
   * update の動作を確認します。
   */
  test("update", async () => {
    class Animal extends FireModel {
      static collectionPath = "Animals";
      static useAutonumber = false;
      static classProps = {
        name: { type: String, default: "", required: true },
        type: { type: String, default: "", required: true },
      };
      static tokenFields = ["name"];
    }
    const model = new Animal({ name: "mike", type: "cat" });
    const docRef = await model.create();
    model.name = "tama";
    await model.update();
    model.name = "mike";
    await model.fetch(model.docId);
    expect(model.name).toBe("tama");
    await docRef.delete();
  });

  /**
   * delete の動作を確認します。
   */
  test("delete document as physical.", async () => {
    const model = new Animal({ name: "mike", type: "cat" });
    const docRef = await model.create();
    await model.delete();
    const isFetched = await model.fetch(docRef.id);
    expect(isFetched).toBe(false);
  });

  /**
   * delete の動作を確認します。
   */
  test("delete document as logical.", async () => {
    class TestModel extends Animal {
      static logicalDelete = true;
    }
    const model = new TestModel({ name: "mike", type: "cat" });
    const docRef = await model.create();
    await model.delete();
    const isFetched = await model.fetch(docRef.id);
    expect(isFetched).toBe(false);
    const archiveDocRef = firestore
      .collection("Animals_archive")
      .doc(docRef.id);
    const archiveDocSnap = await archiveDocRef.get();
    expect(archiveDocSnap.exists).toBe(true);
    await archiveDocRef.delete();
  });

  /**
   * restore の動作を確認します。
   */
  test("restore document.", async () => {
    class TestModel extends Animal {
      static logicalDelete = true;
    }
    const model = new TestModel({ name: "mike", type: "cat" });
    const docRef = await model.create();
    await model.delete();
    const restoreDocRef = await TestModel.restore(docRef.id);
    await restoreDocRef.delete();
  });

  /**
   * subscribe の動作を確認します。
   */
  test("subscribe document.", async () => {
    const model = new Animal({ name: "mike", type: "cat" });
    const docRef = await model.create();
    const otherModel = new Animal();
    expect(() => otherModel.subscribe(docRef.id)).toThrow();
    // await new Promise((resolve) => setTimeout(resolve, 1000));
    // expect(otherModel.name).toBe("mike");
    expect(otherModel.unsubscribe).toThrow();
    await docRef.delete();
  });

  /**
   * subscribeDocs の動作を確認します。
   */
  test("subscribeDocs document.", async () => {
    const model = new Animal();
    expect(model.subscribeDocs).toThrow();
  });

  afterAll(() => {
    functions.cleanup();
  });
});
